"use client";

import Link from "next/link";
import { useEffect, useRef } from "react";

interface NavLink {
	label: string; // Fixed: matches Header.tsx
	href: string;
}

interface MobileMenuProps {
	isOpen: boolean;
	onClose: () => void; // Fixed: matches the prop passed from Header.tsx
	navLinks: NavLink[];
	lang: string; // Fixed: properly receive lang for localized routing
}

export default function MobileMenu({ isOpen, onClose, navLinks, lang }: MobileMenuProps) {
	const menuRef = useRef<HTMLDivElement>(null);

	// Close the menu when the Escape key is pressed
	useEffect(() => {
		const handleKeyDown = (e: KeyboardEvent) => {
			if (e.key === "Escape" && isOpen) {
				onClose();
			}
		};
		document.addEventListener("keydown", handleKeyDown);
		return () => document.removeEventListener("keydown", handleKeyDown);
	}, [isOpen, onClose]);

	if (!isOpen) return null;

	return (
		<div
			className="md:hidden border-b border-gray-200 bg-white absolute w-full z-40 shadow-xl"
			id="mobile-menu"
			ref={menuRef}
			role="dialog"
			aria-modal="true"
			aria-label="Main mobile navigation"
		>
			<div className="px-6 pt-2 pb-6 space-y-1 bg-white">
				{navLinks.map((link) => (
					<Link
						key={link.label} // Fixed: unique key generated by the label text
						href={link.href}
						className="block px-3 py-4 text-base font-medium text-gray-900 hover:text-[var(--accent-teal)] focus:outline-none transition-colors border-b border-gray-100 last:border-none"
						onClick={onClose}
					>
						{link.label}
					</Link>
				))}

				{/* Mobile CTA */}
				<div className="pt-6 pb-2">
					<Link
						href={`/${lang}/contact`}
						className="block w-full text-center text-base font-bold rounded-sm border-2 border-[var(--accent-teal)] bg-[var(--accent-teal)] text-white px-5 py-3 hover:bg-[var(--accent-teal-hover)] hover:border-[var(--accent-teal-hover)] transition-all"
						onClick={onClose}
					>
						Talk to Us
					</Link>
				</div>
			</div>
		</div>
	);
}