import ContentBlock from '@/components/ContentBlock';

export default function PrivacyPage() {
    return (
        <main>
            <ContentBlock title="Privacy Notice" subtitle="Last updated: August 2026">
                <p>ValoraEX Intelligence Ecosystem Limited (“ValoraEX”, “we”, “us” or “our”) respects the privacy of visitors to this website and is committed to handling personal data in accordance with applicable requirements, including the Personal Data (Privacy) Ordinance (Cap. 486) of Hong Kong.</p>

                <h3>1. Information We May Collect</h3>
                <p>Depending on how you use this website or communicate with us, we may collect information including:</p>
                <ul>
                    <li>your name;</li>
                    <li>company or organisation;</li>
                    <li>email address;</li>
                    <li>telephone number, where provided;</li>
                    <li>enquiry type;</li>
                    <li>information contained in your message or enquiry;</li>
                    <li>correspondence between you and ValoraEX; and</li>
                    <li>basic technical or website-usage information where generated by the operation of the website or approved analytics tools.</li>
                </ul>
                <p>Please do not submit confidential, highly sensitive or unnecessary personal information through the general website enquiry form.</p>

                <h3>2. How We Use Information</h3>
                <p>We may use information provided to us for purposes including:</p>
                <ul>
                    <li>responding to enquiries;</li>
                    <li>communicating with you;</li>
                    <li>understanding potential project, service or partnership requirements;</li>
                    <li>administering related business discussions;</li>
                    <li>maintaining appropriate business and enquiry records;</li>
                    <li>improving our website, communications and services;</li>
                    <li>protecting the security and proper operation of our website; and</li>
                    <li>complying with applicable legal, regulatory or administrative requirements.</li>
                </ul>
                <p>We will not use personal data for an unrelated purpose unless permitted by law or appropriate notice and consent have been provided.</p>

                <h3>3. Providing Personal Data</h3>
                <p>Providing personal data through this website is generally voluntary.</p>
                <p>However, if information reasonably required to respond to an enquiry is not provided, we may be unable to respond fully or proceed with the relevant discussion.</p>

                <h3>4. Disclosure and Service Providers</h3>
                <p>Personal data may, where reasonably necessary for the relevant purpose, be accessed by:</p>
                <ul>
                    <li>authorised ValoraEX personnel;</li>
                    <li>contractors or service providers supporting website hosting, technology, communications or enquiry handling;</li>
                    <li>professional advisers where appropriate; and</li>
                    <li>regulatory, governmental, law-enforcement or other parties where disclosure is required or permitted by law.</li>
                </ul>
                <p>We do not sell personal data to advertisers.</p>
                <p>Where external service providers process information on our behalf, we expect them to use the information only for the relevant service and subject to appropriate confidentiality and data-protection arrangements.</p>

                <h3>5. Cookies and Website Analytics</h3>
                <p>This website may use cookies or similar technologies necessary for website functionality and, where implemented, limited analytics or performance measurement.</p>
                <p>Where optional cookies or technologies collect personal data or are used for purposes requiring consent, appropriate notice or choice will be provided in accordance with applicable requirements.</p>

                <h3>6. Retention</h3>
                <p>We will retain personal data only for as long as reasonably necessary for the purpose for which it was collected, any directly related purpose, or applicable legal and business-record requirements.</p>

                <h3>7. Security</h3>
                <p>We take reasonable steps to protect personal data against unauthorised or accidental access, processing, erasure, loss or use.</p>
                <p>However, no internet transmission or electronic storage method can be guaranteed to be completely secure.</p>

                <h3>8. External Websites</h3>
                <p>This website may contain links to third-party websites or platforms.</p>
                <p>ValoraEX is not responsible for the privacy practices, security or content of third-party websites. Visitors should review the privacy information provided by the relevant third party.</p>

                <h3>9. Access and Correction</h3>
                <p>Subject to applicable law, you may request access to or correction of personal data held by ValoraEX.</p>
                <p>Requests may be sent to:</p>
                <p>
                    <strong>ValoraEX Intelligence Ecosystem Limited</strong><br />
                    Email: <strong>hello@valoraex.com</strong>
                </p>
                <p>We may request reasonable information to verify the identity of the person making the request.</p>

                <h3>10. Direct Marketing</h3>
                <p>ValoraEX will not use personal data collected through the general website enquiry form for direct marketing unless the applicable legal requirements have been satisfied.</p>
                <p>If direct-marketing functionality is introduced later, the relevant consent and opt-out arrangements will be separately implemented.</p>

                <h3>11. Changes to this Privacy Notice</h3>
                <p>We may update this Privacy Notice from time to time to reflect changes in our website, services, technology or legal requirements.</p>
                <p>The latest version will be published on this website together with its update date.</p>

                <h3>12. Contact</h3>
                <p>
                    <strong>ValoraEX Intelligence Ecosystem Limited</strong><br />
                    <strong>延昇智能生態有限公司</strong>
                </p>
                <p>Email: <strong>hello@valoraex.com</strong></p>
            </ContentBlock>
        </main>
    );
}